generatorName: typescript-fetch
output: generated/typescript
inputSpec: spec/openapi.json
additionalProperties:
  npmName: "@soroban-identity/client-ts"
  npmVersion: "0.1.0"
  npmRepository: "https://github.com/El-Chapo-Npm/Soroban-Identity.git"
  licenseName: "MIT"
  supportsES6: "true"
  withInterfaces: "true"
  useSingleRequestParameter: "true"
  stringEnums: "true"
  enumPropertyNaming: "PascalCase"
  modelPropertyNaming: "original"